# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1X8ggaxzXcYK1NWkRhjgLBnQqj44and1u
"""

import pandas as pd

url ='/content/Sonar.csv'
df = pd.read_csv(url)
print(df.head())

df.to_csv("output.csv", index=False)

json_data = df.to_json()
df_json = pd.read_json(json_data)
print(df_json.head())

df.to_excel("output.xlsx", index=False)
df_excel = pd.read_excel("output.xlsx")
print(df_excel.head())

from google.colab import drive
drive.mount('/content/drive')